var CANVAS_WIDTH = 600;
var CANVAS_HEIGHT = 150;
var GROUND_LINE_Y = 130;
var PLAYER_WIDTH = 20;
var PLAYER_HEIGHT = 40;
var PLAYER_X = 40;
var PLAYER_GROUND_Y = GROUND_LINE_Y - PLAYER_HEIGHT;
var GRAVITY = 0.6;
var JUMP_VELOCITY = -11;
var OBSTACLE_WIDTH = 16;
var OBSTACLE_MIN_HEIGHT = 20;
var OBSTACLE_MAX_HEIGHT = 40;
var OBSTACLE_SPEED = 4;
var OBSTACLE_MIN_GAP = 90;
var OBSTACLE_MAX_GAP = 220;
var TOTAL_JUMPS_TO_WIN = 18;
var CONFETTI_COUNT = 80;

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    CANVAS_WIDTH: CANVAS_WIDTH,
    CANVAS_HEIGHT: CANVAS_HEIGHT,
    GROUND_LINE_Y: GROUND_LINE_Y,
    PLAYER_WIDTH: PLAYER_WIDTH,
    PLAYER_HEIGHT: PLAYER_HEIGHT,
    PLAYER_X: PLAYER_X,
    PLAYER_GROUND_Y: PLAYER_GROUND_Y,
    GRAVITY: GRAVITY,
    JUMP_VELOCITY: JUMP_VELOCITY,
    OBSTACLE_WIDTH: OBSTACLE_WIDTH,
    OBSTACLE_MIN_HEIGHT: OBSTACLE_MIN_HEIGHT,
    OBSTACLE_MAX_HEIGHT: OBSTACLE_MAX_HEIGHT,
    OBSTACLE_SPEED: OBSTACLE_SPEED,
    OBSTACLE_MIN_GAP: OBSTACLE_MIN_GAP,
    OBSTACLE_MAX_GAP: OBSTACLE_MAX_GAP,
    TOTAL_JUMPS_TO_WIN: TOTAL_JUMPS_TO_WIN,
    CONFETTI_COUNT: CONFETTI_COUNT,
  };
}
