var CANVAS_HEIGHT = 300;
var GROUND_LINE_Y = 260;
var PLAYER_WIDTH = 72;
var PLAYER_HEIGHT = 48;
var PLAYER_X = 80;
var PLAYER_GROUND_Y = GROUND_LINE_Y - PLAYER_HEIGHT;
var GRAVITY = 1.2;
var FALL_GRAVITY = 0.7;
var JUMP_VELOCITY = -17;
var OBSTACLE_WIDTH = 32;
var OBSTACLE_MIN_HEIGHT = 40;
var OBSTACLE_MAX_HEIGHT = 80;
var OBSTACLE_SPEED = 7;
var OBSTACLE_MIN_GAP = 480;
var OBSTACLE_MAX_GAP = 1100;
var TOTAL_JUMPS_TO_WIN = 18;
var CONFETTI_COUNT = 150;
var SKY_COLOR_TOP = "#e6ddf5";
var SKY_COLOR_BOTTOM = "#f7f2ff";
var GROUND_COLOR = "#e8d9b5";
var GROUND_EDGE_COLOR = "#c9b385";
var PLAYER_BODY_COLOR = "#d62828";
var PLAYER_LEG_COLOR = "#8f1d1d";
var RIDER_SUIT_COLOR = "#1d1d1d";
var HELMET_COLOR = "#d62828";

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    CANVAS_HEIGHT: CANVAS_HEIGHT,
    GROUND_LINE_Y: GROUND_LINE_Y,
    PLAYER_WIDTH: PLAYER_WIDTH,
    PLAYER_HEIGHT: PLAYER_HEIGHT,
    PLAYER_X: PLAYER_X,
    PLAYER_GROUND_Y: PLAYER_GROUND_Y,
    GRAVITY: GRAVITY,
    FALL_GRAVITY: FALL_GRAVITY,
    JUMP_VELOCITY: JUMP_VELOCITY,
    OBSTACLE_WIDTH: OBSTACLE_WIDTH,
    OBSTACLE_MIN_HEIGHT: OBSTACLE_MIN_HEIGHT,
    OBSTACLE_MAX_HEIGHT: OBSTACLE_MAX_HEIGHT,
    OBSTACLE_SPEED: OBSTACLE_SPEED,
    OBSTACLE_MIN_GAP: OBSTACLE_MIN_GAP,
    OBSTACLE_MAX_GAP: OBSTACLE_MAX_GAP,
    TOTAL_JUMPS_TO_WIN: TOTAL_JUMPS_TO_WIN,
    CONFETTI_COUNT: CONFETTI_COUNT,
    SKY_COLOR_TOP: SKY_COLOR_TOP,
    SKY_COLOR_BOTTOM: SKY_COLOR_BOTTOM,
    GROUND_COLOR: GROUND_COLOR,
    GROUND_EDGE_COLOR: GROUND_EDGE_COLOR,
    PLAYER_BODY_COLOR: PLAYER_BODY_COLOR,
    PLAYER_LEG_COLOR: PLAYER_LEG_COLOR,
    RIDER_SUIT_COLOR: RIDER_SUIT_COLOR,
    HELMET_COLOR: HELMET_COLOR,
  };
}
